use_frameworks!

target 'BaseMVC_Example' do
  pod 'BaseMVC', :path => '../'

  target 'BaseMVC_Tests' do
    inherit! :search_paths

    pod 'DPNetworking'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'MJExtension'
  end
end
